In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
dataset = pd.read_csv('Logistic_Iris.csv')

In [3]:
x = dataset.iloc[:, [0,1,2,3]].values

In [5]:
y = dataset.iloc[:, 4].values

In [7]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.25, random_state=0)

In [8]:
sc = StandardScaler()

In [10]:
xtrain = sc.fit_transform(xtrain)

In [12]:
xtest = sc.transform(xtest)

In [13]:
classifier = LogisticRegression(random_state = 0)
classifier.fit(xtrain, ytrain)

LogisticRegression(random_state=0)

In [14]:
classifier.classes_

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [15]:
classifier.intercept_

array([-0.3626655 ,  1.68785188, -1.32518638])

In [16]:
classifier.coef_

array([[-0.95553753,  1.15245455, -1.61438718, -1.55955728],
       [ 0.47710429, -0.68052402, -0.19695366, -0.99093571],
       [ 0.47843324, -0.47193053,  1.81134084,  2.55049299]])

In [17]:
classifier.score(xtest, ytest)

0.8421052631578947

In [18]:
y_pred = classifier.predict(xtest)
y_pred

array(['Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor'],
      dtype=object)

In [19]:
print ("Accuracy : ", accuracy_score(ytest, y_pred))

Accuracy :  0.8421052631578947


In [21]:
cm = confusion_matrix(ytest, y_pred)
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[13  1  0]
 [ 0 13  1]
 [ 0  4  6]]
