In [1]:
import numpy as nm
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from matplotlib.colors import ListedColormap
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [3]:
dataset = pd.read_csv("Logistic_Iris.csv")

In [4]:
x = dataset.iloc[:, [0,1,2,3]].values

In [5]:
y = dataset.iloc[:, [4]].values

In [6]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.25, random_state=0)

In [8]:
sc = StandardScaler()
xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)

In [9]:
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(xtrain, ytrain)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=7)

In [10]:
ypred = knn.predict(xtest)

In [11]:
print ("\n\nAccuracy : ", accuracy_score(ytest, ypred)*100)



Accuracy :  92.10526315789474


In [12]:
cm = confusion_matrix(ytest, ypred)
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[14  0  0]
 [ 0 14  0]
 [ 0  3  7]]
